.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. anoncoin_qt test_anoncoin_qt
clean: FORCE
	$(MAKE) -C .. anoncoin_qt_clean test_anoncoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_anoncoin_qt_check
anoncoin-qt anoncoin-qt.exe: FORCE
	 $(MAKE) -C .. anoncoin_qt
