
find_path(QRENCODE_INCLUDE_DIR qrencode.h PATH_SUFFIXES qrencode)
find_library(QRENCODE_LIBRARY qrencode)

if(QRENCODE_INCLUDE_DIR AND QRENCODE_LIBRARY)
    set(QRENCODE_FOUND TRUE)
else()
    set(QRENCODE_FOUND FALSE)
endif()

MARK_AS_ADVANCED(QRENCODE_INCLUDE_DIR QRENCODE_LIBRARY)
